<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-17T14:48:37 IST" name="Default suite" finished-at="2024-04-17T14:49:09 IST" duration-ms="31619">
    <groups>
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:frameworks.tests.SubmitOrderTest@26d9b808]" name="submitOrder" class="frameworks.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-04-17T14:48:37 IST" name="Default test" finished-at="2024-04-17T14:49:09 IST" duration-ms="31619">
      <class name="frameworks.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:frameworks.tests.SubmitOrderTest@26d9b808]" started-at="2024-04-17T14:48:38 IST" name="launchApplication" finished-at="2024-04-17T14:48:48 IST" duration-ms="9817" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:frameworks.tests.SubmitOrderTest@26d9b808]" started-at="2024-04-17T14:48:48 IST" name="submitOrder" data-provider="getData" finished-at="2024-04-17T14:48:56 IST" duration-ms="8069" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Appspass@123, product=ZARA COAT 3, email=taimur@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:frameworks.tests.SubmitOrderTest@26d9b808]" started-at="2024-04-17T14:48:56 IST" name="tearDown" finished-at="2024-04-17T14:48:57 IST" duration-ms="1073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:frameworks.tests.SubmitOrderTest@26d9b808]" started-at="2024-04-17T14:48:57 IST" name="launchApplication" finished-at="2024-04-17T14:49:05 IST" duration-ms="7183" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:frameworks.tests.SubmitOrderTest@26d9b808]" started-at="2024-04-17T14:49:05 IST" name="submitOrder" data-provider="getData" finished-at="2024-04-17T14:49:08 IST" duration-ms="3421" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Priya@1234, product=ADIDAS ORIGINAL, email=pri.luvs@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at frameworks.tests.SubmitOrderTest.submitOrder(SubmitOrderTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:frameworks.tests.SubmitOrderTest@26d9b808]" started-at="2024-04-17T14:49:08 IST" name="tearDown" finished-at="2024-04-17T14:49:09 IST" duration-ms="785" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:frameworks.tests.SubmitOrderTest@26d9b808]" started-at="2024-04-17T14:49:09 IST" name="OrderHistoryTest" finished-at="2024-04-17T14:49:09 IST" depends-on-methods="frameworks.tests.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method frameworks.tests.SubmitOrderTest.OrderHistoryTest() on instance frameworks.tests.SubmitOrderTest@26d9b808 depends on not successfully finished methods 
[frameworks.tests.SubmitOrderTest.submitOrder() on instance frameworks.tests.SubmitOrderTest@26d9b808]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method frameworks.tests.SubmitOrderTest.OrderHistoryTest() on instance frameworks.tests.SubmitOrderTest@26d9b808 depends on not successfully finished methods 
[frameworks.tests.SubmitOrderTest.submitOrder() on instance frameworks.tests.SubmitOrderTest@26d9b808]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- frameworks.tests.SubmitOrderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
